version: "3.9"

services:

  mysql:

    image: mysql:8.4

    container_name: inventory-mysql

    restart: always

    environment:

      MYSQL_ROOT_PASSWORD: rootpassword

      MYSQL_DATABASE: inventory_db

      MYSQL_USER: inventory_user

      MYSQL_PASSWORD: inventory_password

    ports:

      - "3306:3306"

    volumes:

      - mysql-data:/var/lib/mysql

      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:

      - inventory-network



  flask:

    build: .

    container_name: inventory-flask

    restart: always

    ports:

      - "5000:5000"

    depends_on:

      - mysql

    environment:

      MYSQL_HOST: mysql

      MYSQL_USER: inventory_user

      MYSQL_PASSWORD: inventory_password

      MYSQL_DB: inventory_db

      MYSQL_PORT: 3306

      SECRET_KEY: inventory-secret-key

    networks:

      - inventory-network



networks:

  inventory-network:



volumes:

  mysql-data:
